apiVersion: v1
kind: Namespace
metadata:
  name: emr-containers
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: aws-auth
#   namespace: kube-system
# data:
#   mapRoles: |
#     - rolearn: arn:aws:iam::381354187112:role/AWSFargatePodExecutionRole
#       username: system:node:{{SessionName}}
#       groups:
#         - system:bootstrappers
#         - system:nodes
#         - system:node-proxier
#     - rolearn: arn:aws:iam::381354187112:role/EmrEksContainerStack-AdminRole38563C57-19QMBTKS7GF9A
#       username: arn:aws:iam::381354187112:role/EmrEksContainerStack-AdminRole38563C57-19QMBTKS7GF9A
#       groups:
#         - system:masters
#    - rolearn: arn:aws:iam::381354187112:role/aws-service-role/emr-containers.amazonaws.com/AWSServiceRoleForAmazonEMRContainers
#      username: emr-containers
#    - rolearn: arn:aws:iam::381354187112:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_3fe26811bfe496f0/scottlwk
#      username: arn:aws:iam::381354187112:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_3fe26811bfe496f0/scottlwk
#      groups:
#        - system:masters
#   mapUsers: |
#     []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emr-on-eks-job-execution-role
  namespace: emr-containers
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::381354187112:role/AmazonEMRContainersJobExecutionRole'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: emr-containers
  namespace: emr-containers
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  - events
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - annotate
  - patch
  - label
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - describe
  - create
  - edit
  - delete
  - deletecollection
  - annotate
  - patch
  - label
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: emr-containers
  namespace: emr-containers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: emr-containers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: emr-containers